### PR TITLE
Dynamic member route

### PR DESCRIPTION
**Pull request by davish**
Instead of using a query parameter, use dynamic routing that was added in NextJS 9.0: https://nextjs.org/docs#dynamic-routing.

The PR also upgrades `next` to `9.1` from `7.0`.

### CODE REVIEW

**Review by cacabo — APPROVED** [review]
still need to make a decision on the `package-lock.json`. Happy to move over to that just want to make sure (1) `yarn.lock` is deleted and (2) the production build still works

**Comment by davish** [comment]
Pretty sure pennlabs.org was moved over to `npm` a little bit ago, I don't see `yarn.lock` in the repo, but @ArmaanT might be able to confirm that. With regards to clubs though, you're right, and i'll keep using yarn for the time being.

**Comment by ArmaanT** [comment]
@pawalt can confirm, but I'm pretty sure we moved over to just using npm for this repo.

**Comment by pawalt** [comment]
Yup we've moved fully over to NPM. Yarn is gone, and a `package-lock.json` exists.

**Pull request merged**
