### PR TITLE
Update product copy (basics, clubs)

### PR DESCRIPTION
**Pull request by valenciafu**

### CODE REVIEW

**Review by cacabo — APPROVED** [review]
lgtm lgtm

**Comment by cacabo** [comment]
...the issue is that my PR killed you
Do you think you can resolve the merge conflict (basically copy stuff from JSX to JSON) or should I do?

**Comment by cacabo** [comment]
@valenciafu fix fix fix!

**Comment by valenciafu** [comment]
i fix

**Pull request merged**
