### PR TITLE
added nextjs Link element for prefetching

### PR DESCRIPTION
**Pull request by davish**
Use the `<Link>` element provided by NextJS for MUCH faster routing between tabs. The site is super snappy now!

https://nextjs.org/docs#with-link

### CODE REVIEW

**Comment by cacabo** [comment]
What's cookin w/ the CI stuff for the website? Was this ever set up correctly? @davish @ArmaanT @ezwang?

**Comment by cacabo** [comment]
Also maybe we don't want to do it in this commit, but I like having a file for routes where each one is a constant...something along the lines of:

```typescript
import { TId } from '../types/user'
import { withQueryParams } from '../util/helpers'

/**
 * List of all frontend routes
 */

// General
export const HOME_ROUTE = '/'
export const TERMS_ROUTE = '/terms'
export const PRIVACY_ROUTE = '/privacy'

// Account management
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const LOGOUT_ROUTE = '/logout'

// Auth and security
export const AUTH_CHANGE_PASSWORD_ROUTE = '/auth/change-password'
export const AUTH_FORGOT_PASSWORD_ROUTE = '/auth/forgot'
export const AUTH_RESET_PASSWORD_ROUTE = '/auth/reset'

// Account management
export const PROFILE_ROUTE = '/profile'
export const EDIT_PROFILE_ROUTE = '/profile/edit'
export const NEW_WORKOUT_ROUTE = '/workouts/new'
export const SETTINGS_ROUTE = '/settings'

// Workouts
export const WORKOUT_ROUTE = (id: TId): string =>
  withQueryParams('/workouts', { id: `${id}` })
export const EDIT_WORKOUT_ROUTE = (id: TId): string =>
  withQueryParams('/workouts/edit', { id: `${id}` })
```

@davish lmk if you're up for this else I'll put it on my TODO

**Review by cacabo — APPROVED** [review]

**Comment by ArmaanT** [comment]
@cacabo CircleCI is set up in a different branch, but not master, so don't worry about the failed check here. We'll finish setting it up when we move to Kubernetes

**Comment by davish** [comment]
@cacabo the routes constants file looks nice! But yeah, think this would be better for another PR, especially if the site's gonna get another refresh soon.

**Pull request merged**
